// Hono environment for Urdu Core. `Env` (bindings, vars, secrets) is generated by
// `pnpm types` into worker-configuration.d.ts.

export type AppEnv = {
  Bindings: Env;
  Variables: {
    // Set by requireSession for every protected /api/* request.
    sessionId: string;
  };
};
